spring:
  #  配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?charsetEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 80
#  mybatis配置
mybatis:
  mapper-locations: classpath:com/cyn/mapper/*.xml
  type-aliases-package: com.cyn.entity
# 日志处理
logging:
  level:
    com.cyn: debug